language: python
python:
  - "3.6"
script:
  - python square.py
notifications:
# Emails are sent to the committer's git-configured email address by default,
  email:
    on_success: change
    on_failure: always
    
  
    
