version: 2
jobs:
  build:  
    working_directory: ~/public_test
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: |  # use pipenv to install dependencies
            sudo pip install pipenv
            pipenv install
      - run:
        command: |
          pipenv run python test_square.py test

